import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  test: {
    environment: "jsdom",
    include: ["tests/**/*.test.ts", "tests/**/*.test.tsx"],
    setupFiles: ["./tests/setup.ts"],
    testTimeout: 15000,
    clearMocks: true,
    restoreMocks: true,
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      reportsDirectory: "coverage",
      include: [
        "src/infrastructure/api/repositories/ApiDispatchRepository.ts",
        "src/infrastructure/api/repositories/dispatchApi.schema.ts",
        "src/infrastructure/api/withApiLogisticsDispatch.ts",
        "src/modules/logistics/application/mappers/DispatchApiMapper.ts",
        "src/modules/logistics/application/services/DispatchApplicationService.ts",
        "src/modules/logistics/components/DispatchReadPanel.tsx",
        "src/modules/logistics/hooks/dispatchReadIdentity.ts",
        "src/modules/logistics/hooks/dispatchRequestIdentity.ts",
        "src/modules/logistics/hooks/useLogisticsDispatchRead.ts",
        "src/modules/logistics/providers/DispatchMutationCoordinatorProvider.tsx",
        "src/modules/logistics/validation/dispatch.validation.ts",
        "src/core/pricing/promotionApplicability.ts",
        "src/infrastructure/api/repositories/ApiPosRepository.ts",
        "src/infrastructure/api/repositories/posApi.schema.ts",
        "src/infrastructure/api/withApiPos.ts",
        "src/modules/pos/application/mappers/PosCashShiftMapper.ts",
        "src/modules/pos/application/mappers/SaleReversalResultMapper.ts",
        "src/modules/pos/application/services/**/*.ts",
        "src/modules/pos/components/SaleReversalResult.tsx",
        "src/modules/pos/components/CashShiftSummary.tsx",
        "src/modules/pos/components/ReturnSaleDetails.tsx",
        "src/modules/pos/hooks/usePosCashShift.ts",
        "src/modules/pos/hooks/usePosReturns.ts",
        "src/modules/pos/hooks/usePosTerminal.ts",
        "src/modules/pos/hooks/usePosSalesHistory.ts",
        "src/modules/pos/components/PosSalesHistoryModal.tsx",
        "src/modules/pos/components/PosSaleHistoryDetails.tsx",
        // Correcciones de administracion (PR #163).
        "src/app/api/auth/session/branches/route.ts",
        "src/core/media/resolveImageUrlInput.ts",
        "src/infrastructure/api/ApiAuthRepository.ts",
        "src/infrastructure/api/ApiBranchRepository.ts",
        "src/infrastructure/api/apiBranchMapper.ts",
        "src/infrastructure/api/fetchPublicStoreIdentity.ts",
        "src/infrastructure/api/withApiSession.ts",
        "src/modules/administration/application/services/ApiCustomersService.ts",
        "src/modules/administration/application/services/UpdateEmployeeService.ts",
        "src/modules/administration/components/EcommerceConfigForm.tsx",
        "src/modules/administration/components/HeroBannerConfigForm.tsx",
        "src/modules/administration/components/ImageUrlField.tsx",
        "src/modules/administration/hooks/useCustomers.ts",
        "src/modules/administration/hooks/useEcommerceConfig.ts",
        "src/modules/administration/hooks/useEmployees.ts",
        "src/modules/administration/hooks/useHeroBannerConfig.ts",
        "src/modules/auth/application/services/GetInicioBusinessIdentityService.ts",
        "src/modules/auth/hooks/useInicioBusinessIdentity.ts",
        "src/modules/catalog/application/services/GetProductsService.ts",
        "src/shared/navigation/PrivateHeader/ActiveBranchProvider.tsx",
        "src/shared/navigation/PrivateHeader/BranchSelector.tsx",
        // Subida de logo y carrusel del e-commerce.
        "src/infrastructure/api/ApiBusinessConfigRepository.ts",
        "src/infrastructure/api/mediaUrl.ts",
        "src/infrastructure/mock/repositories/MockBusinessConfigRepository.ts",
        "src/modules/administration/application/services/SaveEcommerceConfigService.ts",
        "src/modules/administration/application/services/SaveHeroBannerConfigService.ts",
        "src/modules/storefront/application/services/ApiPublicStorefrontConfigService.ts",
        // Entitlements de roles operativos (Cajero, Inventario, Bodeguero).
        "src/app/api/auth/session/entitlements/route.ts",
        "src/infrastructure/api/ApiSessionEntitlementsClient.ts",
        "src/modules/catalog/application/services/GetProductDetailService.ts",
        "src/modules/inventory/navigation.ts",
        // Historial de Logística (PR #167).
        "src/infrastructure/api/repositories/ApiLogisticsHistoryRepository.ts",
        "src/infrastructure/api/repositories/logisticsHistoryApi.schema.ts",
        "src/infrastructure/api/withApiLogisticsHistory.ts",
        "src/modules/logistics/application/mappers/LogisticsHistoryApiMapper.ts",
        "src/modules/logistics/application/services/GetLogisticsHistoryService.ts",
        "src/modules/logistics/hooks/useLogisticsHistory.ts",
        "src/modules/logistics/components/LogisticsHistoryTable.tsx",
        "src/modules/logistics/components/LogisticsHistoryFilters.tsx",
        "src/modules/logistics/components/LogisticsTracePanel.tsx",
        "src/modules/logistics/pages/LogisticsHistoryPage.tsx",
      ],
    },
  },
});
