export { BusinessConfigPage } from "@/modules/administration/pages/BusinessConfigPage";
export { CashShiftsPage } from "@/modules/administration/pages/CashShiftsPage";
export { DashboardPage } from "@/modules/administration/pages/DashboardPage";
export { ReportsPage } from "@/modules/administration/pages/ReportsPage";
export { EcommerceConfigPage } from "@/modules/administration/pages/EcommerceConfigPage";
export { AuditLogPage } from "@/modules/administration/pages/AuditLogPage";
export { BranchesPage } from "@/modules/administration/pages/BranchesPage";
export { BankAccountsPage } from "@/modules/administration/pages/BankAccountsPage";
export { SuppliersPage } from "@/modules/administration/pages/SuppliersPage";
