"use client";

import Image from "next/image";
import Link from "next/link";
import { StorefrontAvailability } from "@/modules/storefront/components/StorefrontAvailability";
import { useStorefrontProductDetail } from "@/modules/storefront/hooks/useStorefrontProductDetail";
import { useStorefrontCart } from "@/modules/storefront/providers/StorefrontCartProvider";

export function ProductDetailPage({ productId }: { productId: string }) {
  const { data, loading, error, reload } = useStorefrontProductDetail(productId);
  const { addProduct } = useStorefrontCart();
  if (loading) return <main className="mx-auto max-w-5xl px-5 py-12 text-[var(--color-text-muted)]">Cargando producto...</main>;
  if (error || !data) return <main className="mx-auto max-w-5xl px-5 py-12"><h1 className="text-3xl font-black text-[var(--color-text)]">Producto</h1><p className="mt-4 text-[var(--color-text-muted)]">{error ?? "El producto no está disponible."}</p><div className="mt-5 flex gap-3"><button className="rounded-xl bg-[var(--color-primary)] px-4 py-2 font-bold text-[var(--color-topbar)]" onClick={reload} type="button">Reintentar</button><Link className="rounded-xl border border-[var(--color-border)] px-4 py-2 font-bold" href="/catalogo">Volver al catálogo</Link></div></main>;
  const { product, availability, categoryName, media, attributes } = data;
  return <main className="mx-auto max-w-5xl px-5 py-10"><Link className="text-sm font-bold text-[var(--color-title)]" href="/catalogo">← Volver al catálogo</Link><section className="mt-5 grid gap-7 rounded-3xl border border-[var(--color-border)] bg-[var(--color-surface)] p-5 shadow-sm md:grid-cols-[1.05fr_.95fr] md:p-7"><div>{media[0] ? <Image alt={media[0].alt ?? product.name} className="h-72 w-full rounded-2xl bg-slate-50 object-cover md:h-[25rem]" height={400} src={media[0].url} width={512} /> : <div className="flex h-72 items-center justify-center rounded-2xl bg-slate-100 text-sm text-[var(--color-text-muted)]">Sin imagen disponible</div>}</div><div className="flex flex-col">{categoryName ? <p className="text-sm font-bold uppercase tracking-wider text-[var(--color-primary-hover)]">{categoryName}</p> : null}<p className="mt-2 text-sm text-[var(--color-text-muted)]">Código · {product.sku}</p><h1 className="mt-2 text-4xl font-black leading-tight text-[var(--color-text)]">{product.name}</h1>{product.brand ? <p className="mt-3 text-sm text-[var(--color-text-muted)]">Marca · {product.brand}</p> : null}<p className="mt-5 leading-7 text-[var(--color-text-muted)]">{product.description ?? "Sin descripción disponible."}</p><p className="mt-7 text-3xl font-black text-[var(--color-title)]">Q{product.salePrice.toFixed(2)}</p><button className="mt-6 rounded-xl bg-[var(--color-primary)] px-5 py-3 font-bold text-[var(--color-topbar)] transition hover:bg-[var(--color-primary-hover)]" onClick={() => void addProduct(product.id)} type="button">Agregar al carrito</button></div></section>{attributes.length > 0 ? <details className="group mt-6 rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)]" open><summary className="flex cursor-pointer list-none items-center justify-between p-5"><span className="text-xl font-bold text-[var(--color-text)]">Características</span><span className="text-sm font-bold text-[var(--color-title)]">Mostrar / ocultar</span></summary><dl className="grid gap-3 border-t border-[var(--color-border)] p-5 sm:grid-cols-2">{attributes.map((attribute) => <div key={attribute.name} className="rounded-xl bg-slate-50 p-4"><dt className="text-sm text-[var(--color-text-muted)]">{attribute.name}</dt><dd className="mt-1 font-bold text-[var(--color-text)]">{attribute.value}</dd></div>)}</dl></details> : null}{availability ? <StorefrontAvailability branches={availability} /> : null}</main>;
}
